lb:
  image: jwilder/nginx-proxy
  ports:
    - "80:80"
  volumes:
    - "/var/run/docker.sock:/tmp/docker.sock"
redis:
  image: redis
h2:
  image: mikeneck/h2
shop1:
  image: mikeneck/jsug-shop
  links:
    - redis
    - h2
  environment:
    VIRTUAL_HOST: jsug-shop.com
  command:
    --spring.thymeleaf.cache=true
    --logging.level.jdbc.resultsettable=ERROR
    --logging.level.jdbc.sqltiming=ERROR
    --logging.level.org=WARN
    --info.instance.name=shop1
shop2:
  image: mikeneck/jsug-shop
  links:
    - redis
    - h2
  environment:
    VIRTUAL_HOST: jsug-shop.com
  command:
    --spring.thymeleaf.cache=true
    --logging.level.jdbc.resultsettable=ERROR
    --logging.level.jdbc.sqltiming=ERROR
    --logging.level.org=WARN
    --info.instance.name=shop2
shop3:
  image: mikeneck/jsug-shop
  links:
    - redis
    - h2
  environment:
    VIRTUAL_HOST: jsug-shop.com
  command:
    --spring.thymeleaf.cache=true
    --logging.level.jdbc.resultsettable=ERROR
    --logging.level.jdbc.sqltiming=ERROR
    --logging.level.org=WARN
    --info.instance.name=shop3
